plugins:
  - jekyll-paginate

permalink:
  pretty

title:
  'Andrew Yurisich'
tagline:
  'a collection of things'
description:
  ''
url:
  https://andrew.yurisich.com
baseurl:
  '/'
paginate:
  5

exclude:
  ['Makefile']

author:
  name:
    'Andrew Yurisich'
  url:
    https://github.com/Droogans

version:
  0.0.1

github:
  repo:
    https://github.com/Droogans/droogans.github.io
