# Dependencies
markdown:
  redcarpet
highlighter:
  rogue

# Permalinks
permalink:
  pretty

# Setup
title:
  'Andrew Yurisich'
tagline:
  'a collection of things'
description:
  ''
url:
  http://andrew.yurisich.com
baseurl:
  '/'
paginate:
  5

exclude:
  ['Guardfile']

author:
  name:
    'Andrew Yurisich'
  url:
    https://github.com/Droogans

# Custom vars
version:
  0.0.1

github:
  repo:
    https://github.com/Droogans/droogans.github.io
