# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Andrew Yurisich'
tagline:          ''
description:      ''
url:              http://droogans.github.io
paginate:         5

author:
  name:           'Andrew Yurisich'
  url:            https://github.com/Droogans

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Droogans/droogans.github.io
